<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><RootNamespace>OrderBook.UnitTests</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OrderBook/OrderBook.Domain/OrderBook.Domain.csproj" />
    <ProjectReference Include="../../src/OrderBook/OrderBook.Application/OrderBook.Application.csproj" />
    <ProjectReference Include="../../src/OrderBook/OrderBook.Infrastructure/OrderBook.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" /><PackageReference Include="FluentAssertions" />
  </ItemGroup>
</Project>
